[
    {
        "type": "root",
        "tabs": [
            {
                "type": "tab",
                "id": "MUSE",
                "label": "auto",
                "color": "auto",
                "css": "",
                "layout": "",
                "spacing": 0,
                "value": "",
                "precision": 0,
                "address": "/muse/eeg",
                "preArgs": [],
                "target": [],
                "variables": "@{parent.variables}",
                "widgets": [
                    {
                        "type": "meter",
                        "top": 0,
                        "left": 0,
                        "id": "Delta",
                        "width": 50,
                        "height": "auto",
                        "label": "auto",
                        "css": "",
                        "address": "/muse/elements/delta_absolute",
                        "preArgs": [],
                        "widgetId": "",
                        "value": "",
                        "color": "auto",
                        "range": {
                            "min": 0,
                            "max": 1
                        },
                        "logScale": true,
                        "origin": "auto",
                        "unit": "",
                        "alignRight": false,
                        "horizontal": false,
                        "pips": false,
                        "dashed": false,
                        "compact": true,
                        "input": false
                    },
                    {
                        "type": "meter",
                        "top": 0,
                        "left": 50,
                        "id": "Theta",
                        "width": 50,
                        "height": "auto",
                        "label": "auto",
                        "css": "",
                        "address": "/muse/elements/theta_absolute",
                        "preArgs": [],
                        "widgetId": "",
                        "value": "",
                        "color": "auto",
                        "range": {
                            "min": 0,
                            "max": 1
                        },
                        "logScale": true,
                        "origin": "auto",
                        "unit": "",
                        "alignRight": false,
                        "horizontal": false,
                        "pips": false,
                        "dashed": false,
                        "compact": true,
                        "input": false
                    },
                    {
                        "type": "meter",
                        "top": 0,
                        "left": 100,
                        "id": "Alpha",
                        "width": 50,
                        "height": "auto",
                        "label": "auto",
                        "css": "",
                        "address": "/muse/elements/alpha_absolute",
                        "preArgs": [],
                        "widgetId": "",
                        "value": "",
                        "color": "auto",
                        "range": {
                            "min": 0,
                            "max": 1
                        },
                        "logScale": true,
                        "origin": "auto",
                        "unit": "",
                        "alignRight": false,
                        "horizontal": false,
                        "pips": false,
                        "dashed": false,
                        "compact": true,
                        "input": false
                    },
                    {
                        "type": "meter",
                        "top": 0,
                        "left": 150,
                        "id": "Beta",
                        "width": 50,
                        "height": "auto",
                        "label": "auto",
                        "css": "",
                        "address": "/muse/elements/beta_absolute",
                        "preArgs": [],
                        "widgetId": "",
                        "value": "",
                        "color": "auto",
                        "range": {
                            "min": 0,
                            "max": 1
                        },
                        "logScale": true,
                        "origin": "auto",
                        "unit": "",
                        "alignRight": false,
                        "horizontal": false,
                        "pips": false,
                        "dashed": false,
                        "compact": true,
                        "input": false
                    },
                    {
                        "type": "meter",
                        "top": 0,
                        "left": 200,
                        "id": "Gamma",
                        "width": 50,
                        "height": "auto",
                        "label": "auto",
                        "css": "",
                        "address": "/muse/elements/gamma_absolute",
                        "preArgs": [],
                        "widgetId": "",
                        "value": "",
                        "color": "auto",
                        "range": {
                            "min": 0,
                            "max": 1
                        },
                        "logScale": true,
                        "origin": "auto",
                        "unit": "",
                        "alignRight": false,
                        "horizontal": false,
                        "pips": false,
                        "dashed": false,
                        "compact": true,
                        "input": false
                    },
                    {
                        "type": "panel",
                        "top": 340,
                        "left": 0,
                        "id": "panel_1",
                        "width": 1060,
                        "height": 40,
                        "label": false,
                        "color": "auto",
                        "css": "",
                        "scroll": true,
                        "border": true,
                        "layout": "",
                        "spacing": 0,
                        "value": "",
                        "precision": 0,
                        "address": "/panel_1",
                        "preArgs": [],
                        "target": [],
                        "variables": "@{parent.variables}",
                        "widgets": [
                            {
                                "type": "visualizer",
                                "top": 0,
                                "left": 50,
                                "id": "visualizer_2",
                                "width": 1010,
                                "height": 40,
                                "color": "auto",
                                "css": "",
                                "widgetId": "",
                                "duration": 60,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "logScale": true,
                                "pips": false,
                                "value": "",
                                "address": "/muse/elements/theta_absolute",
                                "preArgs": [],
                                "label": false
                            },
                            {
                                "type": "text",
                                "top": 0,
                                "left": 0,
                                "id": "text_2",
                                "width": 50,
                                "height": 40,
                                "label": false,
                                "color": "auto",
                                "css": "",
                                "widgetId": "",
                                "vertical": false,
                                "value": "theta",
                                "preArgs": [],
                                "address": "/alpha"
                            }
                        ],
                        "tabs": []
                    },
                    {
                        "type": "panel",
                        "top": 300,
                        "left": 0,
                        "id": "panel_2",
                        "width": 1060,
                        "height": 40,
                        "label": false,
                        "color": "auto",
                        "css": "",
                        "scroll": true,
                        "border": true,
                        "layout": "",
                        "spacing": 0,
                        "value": "",
                        "precision": 0,
                        "address": "/panel_2",
                        "preArgs": [],
                        "target": [],
                        "variables": "@{parent.variables}",
                        "widgets": [
                            {
                                "type": "visualizer",
                                "top": 0,
                                "left": 50,
                                "id": "visualizer_3",
                                "width": 1010,
                                "height": 40,
                                "color": "auto",
                                "css": "",
                                "widgetId": "",
                                "duration": 60,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "logScale": true,
                                "pips": false,
                                "value": "",
                                "address": "/muse/elements/delta_absolute",
                                "preArgs": [],
                                "label": false
                            },
                            {
                                "type": "text",
                                "top": 0,
                                "left": 0,
                                "id": "text_3",
                                "width": 50,
                                "height": 40,
                                "label": false,
                                "color": "auto",
                                "css": "",
                                "widgetId": "",
                                "vertical": false,
                                "value": "Delta",
                                "preArgs": [],
                                "address": "/alpha"
                            }
                        ],
                        "tabs": []
                    },
                    {
                        "type": "panel",
                        "top": 380,
                        "left": 0,
                        "id": "panel_3",
                        "width": 1060,
                        "height": 40,
                        "label": false,
                        "color": "auto",
                        "css": "",
                        "scroll": true,
                        "border": true,
                        "layout": "",
                        "spacing": 0,
                        "value": "",
                        "precision": 0,
                        "address": "/panel_3",
                        "preArgs": [],
                        "target": [],
                        "variables": "@{parent.variables}",
                        "widgets": [
                            {
                                "type": "visualizer",
                                "top": 0,
                                "left": 50,
                                "id": "visualizer_4",
                                "width": 1010,
                                "height": 40,
                                "color": "auto",
                                "css": "",
                                "widgetId": "",
                                "duration": 60,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "logScale": true,
                                "pips": false,
                                "value": "",
                                "address": "/muse/elements/alpha_absolute",
                                "preArgs": [],
                                "label": false
                            },
                            {
                                "type": "text",
                                "top": 0,
                                "left": 0,
                                "id": "text_4",
                                "width": 50,
                                "height": 40,
                                "label": false,
                                "color": "auto",
                                "css": "",
                                "widgetId": "",
                                "vertical": false,
                                "value": "alpha",
                                "preArgs": [],
                                "address": "/alpha"
                            }
                        ],
                        "tabs": []
                    },
                    {
                        "type": "panel",
                        "top": 420,
                        "left": 0,
                        "id": "panel_4",
                        "width": 1060,
                        "height": 40,
                        "label": false,
                        "color": "auto",
                        "css": "",
                        "scroll": true,
                        "border": true,
                        "layout": "",
                        "spacing": 0,
                        "value": "",
                        "precision": 0,
                        "address": "/panel_4",
                        "preArgs": [],
                        "target": [],
                        "variables": "@{parent.variables}",
                        "widgets": [
                            {
                                "type": "visualizer",
                                "top": 0,
                                "left": 50,
                                "id": "visualizer_5",
                                "width": 1010,
                                "height": 40,
                                "color": "auto",
                                "css": "",
                                "widgetId": "",
                                "duration": 60,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "logScale": true,
                                "pips": false,
                                "value": "",
                                "address": "/muse/elements/beta_absolute",
                                "preArgs": [],
                                "label": false
                            },
                            {
                                "type": "text",
                                "top": 0,
                                "left": 0,
                                "id": "text_5",
                                "width": 50,
                                "height": 40,
                                "label": false,
                                "color": "auto",
                                "css": "",
                                "widgetId": "",
                                "vertical": false,
                                "value": "beta",
                                "preArgs": [],
                                "address": "/alpha"
                            }
                        ],
                        "tabs": []
                    },
                    {
                        "type": "panel",
                        "top": 460,
                        "left": 0,
                        "id": "panel_5",
                        "width": 1060,
                        "height": 40,
                        "label": false,
                        "color": "auto",
                        "css": "",
                        "scroll": true,
                        "border": true,
                        "layout": "",
                        "spacing": 0,
                        "value": "",
                        "precision": 0,
                        "address": "/panel_5",
                        "preArgs": [],
                        "target": [],
                        "variables": "@{parent.variables}",
                        "widgets": [
                            {
                                "type": "visualizer",
                                "top": 0,
                                "left": 50,
                                "id": "visualizer_6",
                                "width": 1010,
                                "height": 40,
                                "color": "auto",
                                "css": "",
                                "widgetId": "",
                                "duration": 60,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "logScale": true,
                                "pips": false,
                                "value": "",
                                "address": "/muse/elements/gamma_absolute",
                                "preArgs": [],
                                "label": false
                            },
                            {
                                "type": "text",
                                "top": 0,
                                "left": 0,
                                "id": "text_6",
                                "width": 50,
                                "height": 40,
                                "label": false,
                                "color": "auto",
                                "css": "",
                                "widgetId": "",
                                "vertical": false,
                                "value": "gamma",
                                "preArgs": [],
                                "address": "/alpha"
                            }
                        ],
                        "tabs": []
                    }
                ],
                "tabs": [],
                "scroll": true
            }
        ],
        "color": "auto",
        "css": "",
        "value": "",
        "precision": 0,
        "address": "/root",
        "preArgs": [],
        "target": [],
        "variables": {},
        "id": "root",
        "scroll": true,
        "label": false
    }
]